import {
  TeamMemberOne,
  TeamMemberTwo,
  TeamMemberThree,
  TeamMemberFour,
  TeamMemberFive,
  TeamMemberSix,
  TeamMemberSeven,
  TeamMemberEight,
  TeamMemberNine,
  TeamMemberTen,
  TeamMemberEleven,
  TeamMemberTwelve,
  TeamMemberThirteen,
  TeamMemberFourteen,
  TeamMemberFifteen,
  TeamMemberSixteen,
  TeamMemberSeventeen,
  TeamMemberEighteen,
  TeamMemberNineteen,
  TeamMemberTwenty,
  TeamMemberTwentyOne,
  TeamMemberTwentyTwo,
  TeamMemberTwentyThree,
  TeamMemberTwentyFour,
  TeamMemberTwentyFive,
  TeamMemberTwentySix,
  TeamMemberTwentySeven,
  TeamMemberTwentyEight,
  TeamMemberTwentyNine,
  TeamMemberThirty,
  TeamMemberThirtyOne,
  TeamMemberThirtyTwo,
  TeamMemberThirtyThree,
  TeamMemberThirtyFour,
  TeamMemberThirtyFive,
  TeamMemberThirtySix,
  TeamMemberThirtySeven,
  TeamMemberThirtyEight,
} from "@/assets/images";

import { IOurTeam } from "./our-team.interface";

export const ourTeamData: IOurTeam[] = [
  { id: 1, img: TeamMemberOne, name: "Rasmus Holst", role: "Founder & CEO" },
  { id: 2, img: TeamMemberTwo, name: "Steven", role: "Head of Operations" },
  { id: 3, img: TeamMemberThree, name: "Nia", role: "Project Manager" },
  {
    id: 4,
    img: TeamMemberFour,
    name: "Jaimee Ligan",
    role: "Head of Associations",
  },
  {
    id: 5,
    img: TeamMemberFive,
    name: "Walter",
    role: "Senior Property Advisor",
  },
  {
    id: 6,
    img: TeamMemberSix,
    name: "Karim el Hassani",
    role: "Senior Property Advisor",
  },
  {
    id: 7,
    img: TeamMemberSeven,
    name: "Thomas",
    role: "Senior Property Advisor",
  },
  { id: 8, img: TeamMemberEight, name: "Ann Dada", role: "Investment Advisor" },
  {
    id: 9,
    img: TeamMemberNine,
    name: "Moha Shkoubi",
    role: "Property Advisor",
  },
  { id: 10, img: TeamMemberTen, name: "Robert", role: "Property Advisor" },
  { id: 11, img: TeamMemberEleven, name: "Elena", role: "Property Advisor" },
  {
    id: 12,
    img: TeamMemberTwelve,
    name: "Roy Weijmar",
    role: "Property Advisor",
  },
  { id: 13, img: TeamMemberThirteen, name: "Famina", role: "Property Advisor" },
  { id: 14, img: TeamMemberFourteen, name: "Lisa", role: "Property Advisor" },
  { id: 15, img: TeamMemberFifteen, name: "Luke", role: "Property Advisor" },
  { id: 16, img: TeamMemberSixteen, name: "Marc", role: "Property Advisor" },
  {
    id: 17,
    img: TeamMemberSeventeen,
    name: "Kasper",
    role: "Property Advisor",
  },
  {
    id: 18,
    img: TeamMemberEighteen,
    name: "Giorgia",
    role: "Property Advisor",
  },
  { id: 19, img: TeamMemberNineteen, name: "Hermon", role: "Founder & CEO" },
  { id: 20, img: TeamMemberTwenty, name: "Regina", role: "Property Advisor" },
  { id: 21, img: TeamMemberTwentyOne, name: "Viven", role: "Property Advisor" },
  { id: 22, img: TeamMemberTwentyTwo, name: "Jens", role: "Property Advisor" },
  {
    id: 23,
    img: TeamMemberTwentyThree,
    name: "Jordan",
    role: "Property Advisor",
  },
  {
    id: 24,
    img: TeamMemberTwentyFour,
    name: "William",
    role: "Property Advisor",
  },
  {
    id: 25,
    img: TeamMemberTwentyFive,
    name: "Ronald",
    role: "Property Advisor",
  },
  {
    id: 26,
    img: TeamMemberTwentySix,
    name: "Willian",
    role: "Property Advisor",
  },
  {
    id: 27,
    img: TeamMemberTwentySeven,
    name: "Blandine",
    role: "Property Advisor",
  },
  {
    id: 28,
    img: TeamMemberTwentyEight,
    name: "Justin",
    role: "Property Advisor",
  },
  { id: 29, img: TeamMemberTwentyNine, name: "Nout", role: "Property Advisor" },
  { id: 30, img: TeamMemberThirty, name: "Glenn", role: "Property Advisor" },
  {
    id: 31,
    img: TeamMemberThirtyOne,
    name: "Carolina",
    role: "Property Advisor",
  },
  { id: 32, img: TeamMemberThirtyTwo, name: "Luis", role: "Property Advisor" },
  { id: 33, img: TeamMemberThirtyThree, name: "Gung", role: "Chief Architect" },
  {
    id: 34,
    img: TeamMemberThirtyFour,
    name: "Mary",
    role: "Head of Customer Service",
  },
  {
    id: 35,
    img: TeamMemberThirtyFive,
    name: "Nani",
    role: "Head of Coco Community",
  },
  { id: 36, img: TeamMemberThirtySix, name: "Alvensia", role: "Brand Manager" },
  {
    id: 37,
    img: TeamMemberThirtySeven,
    name: "Dara",
    role: "Social Media Manager",
  },
  {
    id: 38,
    img: TeamMemberThirtyEight,
    name: "Vander",
    role: "Head of Content",
  },
];
